"""add language support

Revision ID: 53c27a8eb68f
Revises: 82c16ddaee91
Create Date: 2023-08-31 00:45:45.138204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c27a8eb68f'
down_revision: Union[str, None] = '82c16ddaee91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('targetLanguage', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('sourceLanguage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'sourceLanguage')
    op.drop_column('movies', 'targetLanguage')
    # ### end Alembic commands ###
